################################################################################
# VIKUNJA_CXX                             : {g++, clang++}
#   [g++]                                 : {7, 8, 9, 10, 11} <list>
#   [clang++]                             : {4.0, 5.0, 6.0, 7, 8, 9, 10} <list>
# ALPAKA_CXX_STANDARD                     . {17, 20}, optional
# VIKUNJA_BOOST_VERSIONS                  : {1.65.1, 1.66.0, 1.67.0, 1.68.0, 1.69.0, 1.70.0, 1.71.0, 1.72.0, 1.73.0} <list>
# VIKUNJA_BUILD_TYPE                      : {Debug, Release}
# VIKUNJA_CMAKE_ARGS                      : <string>
# VIKUNJA_CXX_TEST                        : {ON}, optional

include:
  - local: '/ci/custom_jobs/integration_test.yml'

stages:
  - validate
  - compile-and-run

################################################################################
# Check code formation with clang-format
# pull request validation:
#   - check C++ code style
pull-request-validation:
  stage: validate
  image: ubuntu:focal
  script:
    - apt update
    # install clang-format-11
    - apt install -y -q wget
    # source: https://github.com/muttleyxd/clang-tools-static-binaries/releases
    - wget https://github.com/muttleyxd/clang-tools-static-binaries/releases/download/master-f3a37dd2/clang-format-12.0.1_linux-amd64
    - mv clang-format-12.0.1_linux-amd64 /usr/bin/clang-format
    - chmod +x /usr/bin/clang-format
    - clang-format --version
    # Check C++ code style
    - source $CI_PROJECT_DIR/ci/check_cpp_code_style.sh
